spring:
  application:
    name: btp-api
  jackson:
    serialization:
      write-dates-as-timestamps: false
  datasource:
    url: jdbc:h2:mem:btpdb;MODE=PostgreSQL;DATABASE_TO_LOWER=TRUE;DEFAULT_NULL_ORDERING=HIGH
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
    open-in-view: false
  h2:
    console:
      enabled: true
  flyway:
    enabled: true

server:
  error:
    include-message: always

springdoc:
  swagger-ui:
    path: /swagger-ui.html

management:
  endpoints:
    web:
      exposure:
        include: health

app:
  security:
    jwt-secret: 0123456789012345678901234567890101234567890123456789012345678901
    jwt-expiration-minutes: 480

---
spring:
  config:
    activate:
      on-profile: prod
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/btp}
    username: ${DB_USERNAME:btp}
    password: ${DB_PASSWORD:btp}
    driver-class-name: org.postgresql.Driver
  h2:
    console:
      enabled: false
